# Generated by Django 2.2.12 on 2023-02-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.ImageField(upload_to='hero')),
                ('hero_title_small', models.CharField(blank=True, max_length=50)),
                ('hero_title_big', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
