# Generated by Django 2.2.12 on 2023-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_img', models.ImageField(blank=True, upload_to='category')),
                ('category_title', models.CharField(max_length=30)),
                ('category_detail', models.CharField(max_length=30)),
            ],
        ),
    ]
