# Generated by Django 2.2.12 on 2023-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(blank=True, upload_to='product')),
                ('product_name', models.CharField(max_length=30)),
                ('product_price', models.CharField(max_length=30)),
                ('product_cat', models.CharField(max_length=30)),
            ],
        ),
    ]
