# Generated by Django 2.2.12 on 2023-02-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_thumb_bottom',
            field=models.ImageField(blank=True, default='', upload_to='product/thumb'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumb_center',
            field=models.ImageField(blank=True, default='', upload_to='product/thumb'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumb_top',
            field=models.ImageField(blank=True, default='', upload_to='product/thumb'),
        ),
    ]
